#define ZZIP_HAVE_STRING_H 1
#define ZZIP_HAVE_SYS_STAT_H 1
#define ZZIP_HAVE_SYS_TYPES_H 1
#define ZZIP_HAVE_DIRECT_H 1
#define ZZIP_HAVE_IO_H 1
#define ZZIP_HAVE_WINDOWS_H 1
#define ZZIP_HAVE_WINBASE_H 1
#define ZZIP_HAVE_WINNT_H 1
#define ZZIP_HAVE_ZLIB_H 1
#define ZZIP_PACKAGE "zziplib-msvc"
#define ZZIP_SIZEOF_INT 4
#define ZZIP_SIZEOF_LONG 4
#define ZZIP_SIZEOF_SHORT 2
#define ZZIP_inline __inline
#define ZZIP_off_t long
#define ZZIP_off64_t __int64
#define ZZIP_ssize_t int
#define ZZIP_restrict
#define ZZIP_VERSION "0.13.72"
